d<-read.table( 'results/walksat/flat100-1_0.0.dat' )
png( 'results/walksat/flat100-1_0.0.png', width = 240, height = 200, units = 'px' )
hist( d$V1, main = 'alpha = 0.0', xlab = 'Satisfied clauses' )
dev.off()
q()